#!/usr/bin/env bash
#
# Summary: Aggregator command to manage all package manager at the same time.
#
# Usage: audio-manipulation <command> [<args>]

set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"")
  audio-manipulation-help
  ;;
* )
  command_path="$(command -v "audio-manipulation-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "audio-manipulation: no such command '$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
