#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: audio-manipulation help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help audio-manipulation
fi

lasher _help audio-manipulation "$command"
